digikala/urls.py
from django.contrib import admin
from django.urls import path,include
from .import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views


app_name = 'shop'

urlpatterns = [
    path('',views.hello_world, name='shop'),
    path('about/',views.about,name='about'),
    path('logout/',views.logout_user,name='logout'),
    path('login/',views.login_user,name='login'),
]

shop/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
import datetime


class Category(models.Model):
    name = models.CharField(max_length=200)
    def __str__(self):
       return self.name

class Customer(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    number = models.CharField(max_length=11)
    email = models.EmailField(max_length=50)
    password = models.CharField(max_length=12)
    


    def __str__(self):
        return f'{self.first_name} {self.last_name}'
    

class Product(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=500, blank=True, null=True)
    price= models.DecimalField(default=0, decimal_places=0,max_digits=12)
    category = models.ForeignKey(Category,on_delete=models.CASCADE, default = 1)
    picture = models.ImageField(upload_to='upload/product/')
    star = models.IntegerField(default=0, validators = [MaxValueValidator(5), MinValueValidator(0)])
    is_sale  =models.BooleanField(default=False)
    sale_price = models.DecimalField(default=0, decimal_places=0, max_digits=12)


    def __str__(self):
        return self.name



class Order(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    address = models.CharField(max_length= 200,default='',blank = False)
    phone = models.CharField(max_length=11,  blank = True)
    date = models.DateField(auto_now_add=True)
    status = models.BooleanField(default=False)
    def __str__(self):
         return self.product

    

shop/views.py
from django.shortcuts import render,HttpResponse,redirect
from .models import Product
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages

def hello_world(request):
    all_products = Product.objects.all()
    return render(request,'index.html',{'products':all_products})

def about(request):
    return render(request,'about.html')

def login_user(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request,username=username,password=password)
        if user is not None:
            login(request,user)
            messages.success(request,('Welcome'))
            return redirect('shop:shop')
        else:
            messages.error(request,('Invalid username or password'))
            return redirect('shop:login')
    else:
         
         return render(request,'login.html')


def logout_user(request):
    logout(request)
    messages.success(request, ('you are logged out'))
    return redirect('shop:shop')

shop/templates/about.html
{% extends 'base.html' %}
{% block content %}
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Shop in style</h1>
            <p class="lead fw-normal text-white-50 mb-0">With this shop hompeage template</p>
        </div>
    </div>
</header>

salam qand
{% endblock %}

shop/templates/base.html
{% load static %}
{% load humanize %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Shop Homepage - Start Bootstrap Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        {% include 'navbar.html' %}

        {% if messages %}

            {% for message in messages %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    {{message}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
            {% endfor %}

        {% endif %}
        <!-- Header-->
        {% block content %}

        {% endblock %}
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">ساخته شده با &hearts; </p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

shop/templates/login.html
{% extends 'base.html' %}
{% block content %}
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">vorod</h1>
            <p class="lead fw-normal text-white-50 mb-0">vorod be safhe</p>
        </div>
    </div>
</header>

<form method = "POST" action="{% url 'shop:login' %}">
    {% csrf_token %}
    <div class="mb-3">
  
      <input type="text" class="form-control" name = "username" placeholder="نام خود را وارد کنید">
     
    </div>
    <div class="mb-3">

      <input type="password" class="form-control" name = "password" placeholder="رمز خود را وارد کنید">
    </div>

    <button type="submit" class="btn btn-secondary">وارد شدن</button>
  </form>
{% endblock %}

shop/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="{% url 'shop:shop' %}">فروشگاه </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="shop/">خانه</a></li>
                <li class="nav-item"><a class="nav-link" href="about/">درباره ما </a></li>


                 {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'shop:logout' %}">خروج</a></li> 
                
                 {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'shop:login' %}">ورود</a></li>
                 {% endif %}


                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">محصولات</a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="#!">All Products</a></li>
                        <li><hr class="dropdown-divider" /></li>
                        <li><a class="dropdown-item" href="#!">Popular Items</a></li>
                        <li><a class="dropdown-item" href="#!">New Arrivals</a></li>
                    </ul>
                </li>
            </ul>
            <form class="d-flex">
                <button class="btn btn-outline-dark" type="submit">
                    <i class="bi-cart-fill me-1"></i>
                    سبد خرید
                    <span class="badge bg-dark text-white ms-1 rounded-pill">0</span>
                </button>
            </form>
        </div>
    </div>
</nav>